config/routes.rb
Rails.application.routes.draw do
  get 'forum/parenting'

  get 'forum/share'

  get 'forum/help'

  get 'chinese/words'

  get 'chinese/story'

  get 'chinese/songs'

  get 'art/animals'

  get 'art/plants'

  get 'art/your_own_project'

  get 'math/addition'

  get 'math/subtraction'

  get 'math/pattern'

  devise_for :users
  resources :homes

  root to: "homes#index"

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #def full_name
    #first_name + " " + last_name
  #end
  has_many :homes
  #def full_name
  #first_name + " " + last_name
  #end
  validates :first_name, :last_name, :profile_name, presence: true
  validates :profile_name, uniqueness: true,
                     format: {
                        with: /a-zA-Z0-9_-/,
                        message: 'Must be formate correctly.'
                     }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/art_controller.rb
class ArtController < ApplicationController
  def animals
  end

  def plants
  end

  def your_own_project
  end
end

app/controllers/chinese_controller.rb
class ChineseController < ApplicationController
  def words
  end

  def story
  end

  def songs
  end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def parenting
  end

  def share
  end

  def help
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :description, :image)
    end
end

app/controllers/math_controller.rb
class MathController < ApplicationController
  def addition
  end

  def subtraction
  end

  def pattern
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
       when :alert
      "alert-error"
       when :notice
      "alert-success"
       else
      ""
    end
  end

end

app/helpers/art_helper.rb
module ArtHelper
end

app/helpers/chinese_helper.rb
module ChineseHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/math_helper.rb
module MathHelper
end

app/views/art/animals.html.erb
<h1>Art#animals</h1>
<p>Find me in app/views/art/animals.html.erb</p>

app/views/art/plants.html.erb
<h1>Art#plants</h1>
<p>Find me in app/views/art/plants.html.erb</p>

app/views/art/your_own_project.html.erb
<h1>Art#your_own_project</h1>
<p>Find me in app/views/art/your_own_project.html.erb</p>

app/views/chinese/songs.html.erb
<h1>Chinese#songs</h1>
<p>Find me in app/views/chinese/songs.html.erb</p>

app/views/chinese/story.html.erb
<h1>Chinese#story</h1>
<p>Find me in app/views/chinese/story.html.erb</p>

app/views/chinese/words.html.erb
<h1>Chinese#words</h1>
<p>Find me in app/views/chinese/words.html.erb</p>

app/views/forum/help.html.erb
<h1>Forum#help</h1>
<p>Find me in app/views/forum/help.html.erb</p>

app/views/forum/parenting.html.erb
<h1>Forum#parenting</h1>
<p>Find me in app/views/forum/parenting.html.erb</p>

app/views/forum/share.html.erb
<h1>Forum#share</h1>
<p>Find me in app/views/forum/share.html.erb</p>

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<div class="page-header">
   <h1>Make learning fun for kids</h1>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="caption">
      <h3>Reading</h3>
      <p>
        Welcome to make learning fun for kids. It is a web application for
        kids to play and learn. You will find the activities including mathematics,
        reading, phonic, Chinese language and others.
      </p>
      <p>
        <a href="#" class="btn btn-primary" role="button">More</a>
      </p>
    </div>
  </div>

   <div class="col-sm-6 col-md-4">
    <div class="caption">
      <h3>Math</h3>
      <p>
        Welcome to make learning fun for kids. It is a web application for
        kids to play and learn. You will find the activities including mathematics,
        reading, phonic, Chinese language and others.
      </p>
      <p>
        <a href="#" class="btn btn-primary" role="button">More</a>
      </p>
      </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="caption">
      <h3>Artwork</h3>
      <p>
        Welcome to make learning fun for kids. It is a web application for
        kids to play and learn. You will find the activities including mathematics,
        reading, phonic, Chinese language and others.
      </p>
      <p>
        <a href="#" class="btn btn-primary" role="button">More</a>
      </p>
      </div>
  </div>

</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @home.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @home.image %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kids Fun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="navbar-header">
    <div class="navbar-inner">
      <nav class="navbar navbar-inverse">
         <div class="container">
           <a href="#" class="navbar-brand">Kids Fun</a>

              <% if user_signed_in? %>
              <ul class="nav pull-right">
              <li><%= link_to current_user.email, edit_user_registration_path %></li>
            </ul>
              <ul class="nav pull-right">
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
            <% else %>
            <ul class="nav pull-right">
               <li><%= link_to "Register", new_user_registration_path %></li>
             </ul>
             <ul class="nav pull-right">
               <li><%= link_to "Log in", new_user_session_path %></li>
             </ul>
              <% end %>

             <ul class="nav navbar-nav">

               <li role="presentation" class="active"><%= link_to "Home", homes_path %></li>
                   <li role="presentation" class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                      aria-haspopup="true" aria-expanded="false">Math<span class="caret"></span>
                     </a>
                       <ul class="dropdown-menu">
                         <li><%= link_to "Addition", math_addition_path %></li>
                         <li><%= link_to "Subtraction", math_subtraction_path %></li>
                         <li><%= link_to "Pattern", math_pattern_path %></li>
                       </ul>
                   </li>
               <li role="presentation" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                      aria-haspopup="true" aria-expanded="false">Art<span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "Animals", art_animals_path %></li>
                      <li><%= link_to "Plants", art_plants_path %></li>
                      <li><%= link_to "Your own projects", art_your_own_project_path %></li>
                  </ul>
                </li>
                <li role="presentation" class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">Chinese<span class="caret"></span>
                   </a>
                   <ul class="dropdown-menu">
                       <li><%= link_to "Words", chinese_songs_path %></li>
                       <li><%= link_to "Stories", chinese_story_path %></li>
                       <li><%= link_to "Songs", chinese_words_path %></li>
                   </ul>
                 </li>
                 <li role="presentation" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                        aria-haspopup="true" aria-expanded="false">Forum<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Parenting", forum_parenting_path %></li>
                        <li><%= link_to "Share", forum_share_path %></li>
                        <li><%= link_to "Help", forum_help_path %></li>
                    </ul>
                  </li>
             </ul>

           <div class="collapse navbar-collapse">
            <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
          </div>

         </div>
      </nav>
    </div>
  </div>

  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>" role="alert">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/math/addition.html.erb
<h1>Math#addition</h1>
<p>Find me in app/views/math/addition.html.erb</p>

app/views/math/pattern.html.erb
<h1>Math#pattern</h1>
<p>Find me in app/views/math/pattern.html.erb</p>

app/views/math/subtraction.html.erb
<h1>Math#subtraction</h1>
<p>Find me in app/views/math/subtraction.html.erb</p>